development:
  AWS_ACCESS_KEY_ID: 'AKIAY5LTJWPB5XGMU4DH'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'ssvanduy'
test:
  AWS_ACCESS_KEY_ID: 'AKIAY5LTJWPB5XGMU4DH'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'projectmeal-dev'
production:
  AWS_ACCESS_KEY_ID: 'AKIAY5LTJWPB5XGMU4DH'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'projectmeal-production'